### ISSUE TITLE
which version is your gensim?

### ISSUE THREAD

**Issue by wxl1351641822** [nju-websoft/OpenEA#25]
I have a error:

`Traceback (most recent call last):
  File "main_from_args.py", line 94, in <module>
    model.init()
  File "/data/home/wuyuming/wxl/OpenEA-master/src/openea/approaches/multi_ke.py", line 327, in init
    self._generate_literal_vectors()
  File "/data/home/wuyuming/wxl/OpenEA-master/src/openea/approaches/multi_ke.py", line 404, in _generate_literal_vectors
    literal_encoder = LiteralEncoder(self.literal_list, word2vec, self.args, 300)
  File "/data/home/wuyuming/wxl/OpenEA-master/src/openea/approaches/literal_encoder.py", line 198, in __init__
    self.word2vec = generate_unlisted_word2vec(word2vec, literal_list, word2vec_dimension)
  File "/data/home/wuyuming/wxl/OpenEA-master/src/openea/approaches/literal_encoder.py", line 175, in generate_unlisted_word2vec
    model = Word2Vec(char_sequences, size=vector_dimension, window=5, min_count=1)
TypeError: __init__() got an unexpected keyword argument 'size'`

**Comment by sunzequn** [comment]
Hi,

Sorry for the late reply.

You can use the 3.8.3 version.

Best,

Zequn
