### ISSUE TITLE
AttributeError: 'Graph' object has no attribute 'label'

### ISSUE THREAD

**Issue by youxingtian** [nju-websoft/OpenEA#52]
I run the main.py demo,but I get the error!
```
Traceback (most recent call last):
  File "/Users/youbo/PycharmProjects/demo/others/OpenEA-tutorial/ontology_matching/src/main.py", line 33, in <module>
    main()
  File "/Users/youbo/PycharmProjects/demo/others/OpenEA-tutorial/ontology_matching/src/main.py", line 17, in main
    src_rdf = RdfParser(src_file, 'http://oaei.ontologymatching.org/2007/benchmarks/101/onto.rdf#')
  File "/Users/youbo/PycharmProjects/demo/others/OpenEA-tutorial/ontology_matching/src/data_input.py", line 26, in __init__
    self.class_labels = [self._graph.label(uri) for uri in self.class_uris]
  File "/Users/youbo/PycharmProjects/demo/others/OpenEA-tutorial/ontology_matching/src/data_input.py", line 26, in <listcomp>
    self.class_labels = [self._graph.label(uri) for uri in self.class_uris]
AttributeError: 'Graph' object has no attribute 'label'
```

**Comment by sunzequn** [comment]
Hi,

Thanks for your interest in our work. This issue may be caused by rdflib. Which version do you use?
