### ISSUE TITLE
ValueError: Cannot feed value of shape (20480,) for Tensor triple_placeholder/Variable/Read/ReadVariableOp:0, which has shape (1,)

### ISSUE THREAD

**Issue by delicate00** [nju-websoft/OpenEA#57]
运行tutorial/entity_alignment/main.py时报错为
Traceback (most recent call last):
  File "D:\WYN\OpenEA-master\OpenEA-master\tutorial\entity_alignment\main.py", line 99, in <module>
    model.run()
  File "D:\WYN\OpenEA-master\OpenEA-master\tutorial\entity_alignment\mtranse.py", line 335, in run
    self.launch_training_1epo(i, triple_steps, steps_tasks, training_batch_queue, neighbors1, neighbors2)
  File "D:\WYN\OpenEA-master\OpenEA-master\tutorial\entity_alignment\mtranse.py", line 234, in launch_training_1epo
    self.launch_embed_training_1epo(epoch, triple_steps, steps_tasks, training_batch_queue, neighbors1, neighbors2)
  File "D:\WYN\OpenEA-master\OpenEA-master\tutorial\entity_alignment\mtranse.py", line 250, in launch_embed_training_1epo
    batch_loss, _ = self.session.run(fetches=[self.triple_loss, self.triple_optimizer],
  File "C:\ProgramData\Anaconda3\envs\openea\lib\site-packages\tensorflow\python\client\session.py", line 968, in run
    result = self._run(None, fetches, feed_dict, options_ptr,
  File "C:\ProgramData\Anaconda3\envs\openea\lib\site-packages\tensorflow\python\client\session.py", line 1165, in _run
    raise ValueError(
ValueError: Cannot feed value of shape (20480,) for Tensor triple_placeholder/Variable/Read/ReadVariableOp:0, which has shape (1,)
如何解决？

**Comment by delicate00** [comment]
解决了，还是tensorflow版本的问题
